### ISSUE TITLE
Generate galaxy catalog on lightcone

### ISSUE THREAD

**Issue by katrinheitmann** [LSSTDESC/DC2_Repo#10]
After all the galaxies have been assigned to their positions using the core tracking approach, the lightcone code is run again to produce the galaxy lightcone

**Comment by katrinheitmann** [comment]
Lightcone from the  galaxy snapshots was created. Now the last step is to integrate everything and then ingest it into DESCQA2

**Comment by katrinheitmann** [comment]
![lighc](https://user-images.githubusercontent.com/12860812/31975817-5be8e030-b8f9-11e7-9f23-d686e79aecfb.png)
Just for fun a picture of the galaxy positions in most closely to z=0

**Comment by cwwalter** [comment]
Super cool!
