### ISSUE TITLE
Lens ids in PhoSim

### ISSUE THREAD

**Issue by katrinheitmann** [LSSTDESC/DC2_Repo#101]
Check that problem with lens IDs in PhoSim was fixed (floats)

**Comment by katrinheitmann** [comment]
@danielsf I think this was just a check you wanted to do Scott, right? Did you have a chance to look into it? Thanks very much!

**Comment by jbkalmbach** [comment]
If somebody is willing to do a quick run of phosim I can give them a very short test catalog with the longer ids.

**Comment by katrinheitmann** [comment]
@johnrpeterson @sembrosk @TomGlanzman Could one of you please do that test with Bryce? Thanks a bunch!

**Comment by TomGlanzman** [comment]
Sure, I can help with this.  @jbkalmbach tell me what needs doing...

**Comment by jbkalmbach** [comment]
Ok, this should run and @danielsf @rbiswas4 can correct me if I'm wrong, but I think the issue is we want to make sure the objectIds from this catalog are the same in the source files phosim returns.

[phosim_cat_1418971.txt](https://github.com/LSSTDESC/DC2_Repo/files/1658697/phosim_cat_1418971.txt)

**Comment by jbkalmbach** [comment]
The main ones to look at are the sprinkled objects at the bottom of the catalog with the longest ids.

**Comment by danielsf** [comment]
I agree that that catalog will plumb the problem.  We are trying to see if PhoSim can handle IDs that are greater than `2**53 ~ 10**15`

**Comment by katrinheitmann** [comment]
Any results on this? Thanks!

**Comment by TomGlanzman** [comment]
A test run (sensor R22_S11) using @jbkalmbach 's instanceCatalog started a couple hours ago and is still running (using 8-threads).  ETA probably about noon Pacific.

**Comment by TomGlanzman** [comment]
@jbkalmbach The phoSim test completed.  Please take a look at the phosim output here:  NERSC:/global/homes/g/glanzman/projects/catTest
(There may be a permissions issue; if so, let me know.)

**Comment by jbkalmbach** [comment]
Yes, there is a permissions issue. I can't access the folder.

**Comment by jbkalmbach** [comment]
We need the centroid file to check and I'm not sure I see it there @TomGlanzman

**Comment by TomGlanzman** [comment]
No, by default phoSim does not create a centroid file.  This directive must go into the command/override file.  Is there anything else needed before I rerun?

**Comment by jbkalmbach** [comment]
Ah, that's my fault. Sorry about that. @danielsf @rbiswas4 We just need the centroid file to check, right?

Also, I don't think we need everything turned on to check this. I think we could do a bare bones run and check the centroid files and that would be fine.

**Comment by TomGlanzman** [comment]
Well, in the interests of getting started, I've gone ahead and restarted a new test run -- with centroid files enabled, and with the 'quick background'.  Hopefully it will conclude in a couple of hours, if not earlier.

**Comment by jbkalmbach** [comment]
Thanks to @TomGlanzman I was able to check the centroid file and can confirm that there are ids accurately appearing that are greater than 10**15 that correspond to the sprinkled objects.
