### ISSUE TITLE
Set up visit list for Run 1.1p

### ISSUE THREAD

**Issue by katrinheitmann** [LSSTDESC/DC2_Repo#103]

**Comment by rbiswas4** [comment]
This probably depends on #98 and #108 but I think we have a deadline of 6pm ET Jan 22?

The outputs should be two files:
- [ ]`Run1.1VisitsWFD_vn.csv`
- [ ] `Run1.1VisitsuDDF_vn.csv`

**Comment by katrinheitmann** [comment]
@rbiswas4 If I understand correctly, this is now taken care of with the Humna's contribution in #108, right? I am closing this now (feel free to reopen it if that's not correct).

**Comment by rbiswas4** [comment]
Actually, there is another step that is necessary. Humna's contribution will close #108 and should be done at the closing of the PR she started automatically.
