### ISSUE TITLE
PhoSim final tasks before starting Run 1.1p

### ISSUE THREAD

**Issue by katrinheitmann** [LSSTDESC/DC2_Repo#104]
In this epic we collect the final tasks regarding phosim

**Comment by katrinheitmann** [comment]
All issues in this epic have been closed, so closing this epic for now as well. Double check one more time with @TomGlanzman, @rbiswas4, and @jchiang87 that everything is in place.

**Comment by cwwalter** [comment]
We still need documentation of the values in the instrument directory.  The table in this 1.1 document lists the files (but not values) and gives references to look things up that don't contain actual description (like the hot column rate).  Also a few things are missing (like filter information for the WGs).  

Just checking: do you want to document that in the main document and then just specify where things are located in this one? Thanks.

**Comment by katrinheitmann** [comment]
Is there much added value to put the actual values for in the document 
itself? We have the link to the files that are used and they can be 
easily looked up. So we thought just pointing to the files in the DESC 
repo where the run is done would be enough.

What is the main document?

**Comment by cwwalter** [comment]
> Is there much added value to put the actual values for in the document
> itself? 

Hi Katrin,

I think yes.  Aside from the issues and missing items I have previously described determining the configuration we want to use, the issue is the analysis and technical groups need a place to find this information when they need/ask for it.  

I feel that telling them that they should read the segmentation.txt file in the instrument directory of the PhoSim release we used at NESRC is not a proper solution. Our job is to make that information available to them.  Also the table has columns that say "documentation" and that would lead you to believe you could find that information if you follow the reference but it is not true (at least in the case I looked at). 

> What is the main document?

I meant did you mean this document was just for us and the main roadmap document I started was for users and you wanted to put information there.

**Comment by katrinheitmann** [comment]
No, I don't actually really want to put that information anywhere beyond where it is now. The treering parameters are short but some of the other files are really long tables. So I think having them in the file system where they can be looked up is the best thing to do. It is the DESC directory, everybody has access to. They should be with the files that go into the run -- when I run code, I always do it like that -- I make sure that I freeze a directory with all inputs for good and keep it there. Copying and pasting and formatting them into a tex document seems weird. If we keep them with the code and the executable and logs etc I think that's best. What are the missing items (beyond the detailed descriptions that we do not need for the current purpose)?  You are not asking us to copy and paste 200 parameters from Galaticus in there either. Again, the files need to be frozen, tagged etc for as long as the run is in use but I don't see putting those files into a document makes sense.

**Comment by katrinheitmann** [comment]
Also, when you write code, you make sure the parameters are properly set and validated. That's what is in the paper description that is noted in the file.

**Comment by cwwalter** [comment]
I am honestly not trying to be difficult here.  I am trying to make the output actually usable for real analysis for the working groups,.

I'm obviously not suggesting we write down 200 numbers in a  giant table, but most of the numbers aren't like that.  I really don't think asking people to read the segmentation.txt file is acceptable.  First of all the file is very hard to read and parse as a human.  I just spent 10 minutes going back and looking at it again, trying to count out column entries by hand.

For example, as far as I can tell, the hot pixel and column rate are still all set to a single number (0.00000012).  So, I am suggesting that is the number we write down.  What is that number's units? I don't know.  We should find out and document it.  

For the crosstalk: If people want details there are indeed going to have to look in the file but we should at least document what the format is so people can figure it out.  What is the "18" before the numbers that look like the correlations but is listed in the x-talk section? What really are those numbers and how are they normalized?  I personally would probably would put an example in of one sensor block so people could figure out how to read it.   Alternatively, we should document what system engineering document PhoSim took the numbers from so people can just look them up there.
 
What if the PZ group wants to know which of they system filter throughput files versions we used for when they are trying to debug their analysis so they have a piece they understand?  Can they figure it out by looking in the directory?  I personally can't.  

You saw the discussion about the tree rings above. 

The way John did this is all very good and it makes sense for running the program.  Please don't take this as some sort of criticism of PhoSim.   But, it does not have the information needed for users to use it without making mistakes or being incapable of getting the information they need.   This is what I asking we write down.  If there are other documents that really actually explains how to read these numbers (and it is complicated) that is fine too we can point to a table or page number in it.

**Comment by cwwalter** [comment]
Also, just to clear, now that we are all on the same page for #66, I am happy for going ahead with starting R1.1.  My comments here are all now about documenting selected important configuration options that people might need for the validation and evaluation.

**Comment by katrinheitmann** [comment]
ok, since this epic is really for phosim being ready for Run 1.1p (final task before starting) and we all agree now it is, I'll close it again.
