### ISSUE TITLE
PhoSim speckle issue

### ISSUE THREAD

**Issue by katrinheitmann** [LSSTDESC/DC2_Repo#105]
Fix speckle issue that appears to be in Run 1.0 on the NERSC systems

**Comment by johnrpeterson** [comment]
resolved with release of phosim v3.7.8.

**Comment by SimonKrughoff** [comment]
Actually, can we leave this open until @TomGlanzman and/or @sethdigel can confirm that this does indeed fix the issue they were seeing?

**Comment by sethdigel** [comment]
Tom re-ran all of the sensor visits from OpSim ID 151687 with v3.7.8.  I searched the FITS images for indications of individual pixels way out of agreement with their neighbors, with the same algorithm that I used before.  None of the 189 sensor visits has more than 109 pixels flagged, and the median is 58, so there's no sign of speckling.  Some of the sensor visits in the previous version had several thousand stand-out pixels.

**Comment by katrinheitmann** [comment]
Excellent! Let's close it again then :-)
