### ISSUE TITLE
amplifier files

### ISSUE THREAD

**Issue by katrinheitmann** [LSSTDESC/DC2_Repo#106]
Decide whether to simulate amplifiers

**Comment by SimonKrughoff** [comment]
I feel like we need to decide this sooner rather than later.  Maybe we could have a phonecon sometime this week to take a decision.  My stance is that, if we can't be assured that we will get he calibration products we need, we should just stick with eimages.

**Comment by drphilmarshall** [comment]
Well - we do still need to start getting some practice with ISR! Can we
simulate both, and fall back to e-image processing if the calibration
products really don't give sufficiently good results? I would think Run 1.1
was a good time to do a small-scale experiment to inform Run 2 on this.

**Comment by cwwalter** [comment]
> The problem really is that we don't have a reliable method to get calibration products (specifically flats). I haven't seen the data we need to do ISR. Maybe @cwwalter knows more.

Well... the SAWG group and others are working on this now.  Eventually, we have to get this to work.  DC2 will be around for a while;  So, even if it takes a bit to be able to use it I think we should go ahead and produce them and learn how to run ISR.
 
Just to get some more info: I think making flats for things like vignetting is already doable.  Getting versions suitable for things like BF correction should make more time.  

So, I think the question to ask is: 

- What do we really need to run ISR? Are there any effects which we need to make sure look reasonable now before we use them? I think if we know that we can be more specific in our discussion.

**Comment by katrinheitmann** [comment]
One thing we should keep in mind: I think we have enough resources to 
redo Run 1.1 if we find we need something else that we didn't do 
originally. And in this way, whatever we decide for this first Run 1.1 
does not necessarily set Run 2.0 in stone. Just to put people's mind at 
ease that we can still change our minds between now and April about some 
settings/outputs.

**Comment by SimonKrughoff** [comment]
> What do we really need to run ISR? 
We need multiple (10?) realizations of each data product for each amp in each band (for zeros and darks we only need one band).  In the past, the phosim team have produced something that looked a little like a master (stacked) flat, but that won't work.  We need to do the stacking ourselves to make sure we understand what went into it.

We may also need flats as a function of rotator angle since there is an imprint from the spider on the illumination pattern.

**Comment by astrostubbs** [comment]
Actually I think you likely need to worry more about the rotation of diffraction spikes around bright stars, especially in difference images. Does PhoSim do that calculation? 
C
 
Christopher Stubbs
Samuel C. Moncher Professor of Physics and of Astronomy
17 Oxford Street
Harvard University
Cambridge MA 02138
stubbs@physics.harvard.edu

Think this email is terse? Here's why:
http://www.emailcharter.org

**Comment by cwwalter** [comment]
Simon: Great.  Can you start an issue with a  checkbox list somewhere so we can capture this?

**Comment by SimonKrughoff** [comment]
@astrostubbs good point.  It does do that calculation.

@cwwalter sure.

**Comment by RobertLuptonTheGood** [comment]
I think we should run the ISR if we can get semi-decent calib products.  For ISR we don't need things like the correlations in the flats right (we're not doing brighter-fatter, right?).

					R

**Comment by SimonKrughoff** [comment]
I believe the plan is to do brighter-fatter.  See discussion in #66.

**Comment by drphilmarshall** [comment]
To clarify: I understood there to be support for including the BF effect in
the simulated images, even if we don't attempt to correct for it with the
DM stack. It's a small effect, and adds to the legacy value of the images.
(Interested to hear how useful it is for the DM team to have simulated
images with the BF effect in them, for testing/development.)

**Comment by johnrpeterson** [comment]
So for PhoSim the amplifier files are nearly negligible CPU cost to generate, and there can be very large numbers of "quick background" flats generated since that would be small CPU cost compared to the total data challenge.  So i think it is possible to both: 1) run it through DM both through ISR from amplifier and 2) not through ISR with the e-images.

**Comment by cwwalter** [comment]
Yes, we are planning to have BF on.  We hope to have both calibration products and the DM correction to apply them soon.  As Phil says, in any case we will check the results without the correction.

**Comment by RobertLuptonTheGood** [comment]
If you don't correct BF it messes up your photometry (c. 3% in the HSC chips).  We have code to fix this (or enough to make HSC happy), and are just porting the code to build the coefficients too.  So if the flats are correct, we'll be OK.

					R

**Comment by johnrpeterson** [comment]
also, if we are going to use flats with DM, you might want to turn on "contaminationmode 1" in phosim.

**Comment by RobertLuptonTheGood** [comment]
What does "contaminationmode 1" do?

**Comment by johnrpeterson** [comment]
dust/debris/condensation

**Comment by RobertLuptonTheGood** [comment]
I don't think we want to turn that on.  I don't *ever* want to deal with condensation (fix the camera!), and I don't have LSST code to track dust etc. just now.   If it's all constant and gray then it isn't very interesting but we can handle it if it makes people happy.

**Comment by johnrpeterson** [comment]
ok, then maybe better to keep it off.

**Comment by katrinheitmann** [comment]
To summarize the discussion here: (i) We will simulate both, and fall back to e-image processing if the calibration products really don't give sufficiently good results. (ii) We keep contaminationmode 0 to not include dust/debris/condensation. (iii) As discussed before, we will switched on BF. 
Given Simon's list in #111, I propose to close this issue. If there are no more comments or questions about these points, I'll close this issue now. Please feel free to reopen if needed.
