### ISSUE TITLE
Rotation + translation CatSim validation/verification

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/DC2_Repo#112]
As presented during the second DC2 telecon (Jan 19th) CatSim adds a translation and rotation to the extragalactic catalogs. I was thinking about checking the 2 point shape-shape, shape-counts and counts-counts correlations (already in DESCQA I think) and compare with the correlations computed for the extragalactic catalogs but, are there any other tests that you want to see/do to make sure that this doesn't affect your science/this is done correctly?

@LSSTDESC/wg-conveners @rmandelb @katrinheitmann @drphilmarshall

**Comment by katrinheitmann** [comment]
I am not sure we should spend too much time on this besides doing a sanity check that it was rotated correctly. This will not happen for DC2 (since we now know that we shouldn't just cut out something without asking first ;-) ).

**Comment by danielsf** [comment]
Yes. It can be closed.
