### ISSUE TITLE
DRP Catalog Services

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/DC2_Repo#119]
The DRP processing will produce FITS tables of various outputs --- information on visits, observing conditions, source and object fluxes, positions, shapes --- and DESC will need to repackage this info in order to make it available to the Science working groups for their pipelines.

**Comment by katrinheitmann** [comment]
After checking with @jchiang87 closing this issue for now. The data access task force is now responsible for these kind of tasks and is starting new issues.
