### ISSUE TITLE
Move to making absolute skymaps with `makeSkyMap.py`

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/DC2_Repo#121]
In #79 @nicolaschotard writes:

> the sky map that we will make should be absolute (using makeSkyMap.py and the appropriate configuration, e.g. for a ring sky map as for HSC and now CFHT reprocessing) instead of relative to the field (with makeDiscreteSkyMap.py). It would ensure that the sky map won't depend on the list of input visits, and thus on the time and place the reprocessing happens.

Issuing this as a needed edit to the cookbook in https://github.com/LSSTDESC/DC2_Repo/blob/issue/73/cookbook/Notebooks/DC2Cookbook.ipynb

Nicolas, would you be willing to take this on, please? Thanks!

**Comment by drphilmarshall** [comment]
Thanks for the contribution, @nicolaschotard ! I made review comments in PR #124 , cc-ing Jim for comment. Now that you have merged into the main dev branch you or he can make those edits more directly. Can you report to this thread when they are done, so I can then close this out? Thanks! :-)

**Comment by heather999** [comment]
This issue was moved to LSSTDESC/ImageProcessingPipelines#7
