### ISSUE TITLE
Describe use of `ingestImages.py`

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/DC2_Repo#122]
Noted by @boutigny as a missing part of the cookbook in https://github.com/LSSTDESC/DC2_Repo/blob/issue/73/cookbook/Notebooks/DC2Cookbook.ipynb

@SimonKrughoff is this an easy upgrade?

**Comment by SimonKrughoff** [comment]
I think so, but I think it may be worth reworking the architecture of the cookbook as a whole rather than upgrading piecemeal.

**Comment by drphilmarshall** [comment]
I think we are open to good suggestions of that form! We'd need to merge
carefully though (and ipynb is not the easiest to merge, just as a warning).

**Comment by SimonKrughoff** [comment]
OK, maybe we should carry out individual updates, and merge as a "big bang" down the road.

**Comment by drphilmarshall** [comment]
Sounds good. I can help with any big merges.

**Comment by nicolaschotard** [comment]
It might be easier to work on a simple `.md` or `.rst` file instead of a `ipynb` one.

**Comment by heather999** [comment]
This issue was moved to LSSTDESC/ImageProcessingPipelines#6
