### ISSUE TITLE
Weird features observed on phosim simulated bright stars 

### ISSUE THREAD

**Issue by boutigny** [LSSTDESC/DC2_Repo#127]
Looking at the following eImage: /global/projecta/projectdirs/lsst/production/DC2/Run1.0/DC2-phoSim-2-r/output/000000/lsst_e_151687_f2_R43_S11_E000.fits.gz we can see strange features on bright objects.
 
As illustrated in the attached screen shot, some stars show a saturation at 34,464 ADU while some adjacent pixels have higher values. These very bright stars could also have pixels with very low values close to saturated pixels. These low pixels embedded in saturated objects may falsify the cosmic ray detection and lead to weird pixel interpolation.

![screenshot from 2018-01-29 18-45-35](https://user-images.githubusercontent.com/5713323/35526431-a48cc976-0527-11e8-888b-7764edb1305b.png)

**Comment by sethdigel** [comment]
Interesting.  What are the pixel coordinates of the star?  I just read that file and am not seeing any pixels with value 34464.  Here's the histogram, with bin width = 1 ADU.

<img width="827" alt="pixel_dist_lsst_e_151687_f2_r43_s11_e000" src="https://user-images.githubusercontent.com/6035835/35527141-9e8e6348-04de-11e8-9cd5-e3199d677c02.png">

**Comment by boutigny** [comment]
Interesting indeed !
The pixel coordinates are in the table in the image above

**Comment by boutigny** [comment]
Robert Lupton just noticed that 100000 - 34464 == 65536 == 2^16

**Comment by sethdigel** [comment]
Ah, I think that's the answer.  I found the star (sorry for my confusion about reading the table - I had not seen one of those before in ds9) and it looks just uniformly saturated at 100,000 at its core.

**Comment by cwwalter** [comment]
This is due to reading the data into DM where an integer truncation is happening.  DS9 alone looks fine.

Closing this issue.

**Comment by SimonKrughoff** [comment]
I will look at how to fix this on the DM side.
