### ISSUE TITLE
Track Phosim electronics orientation issue

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/DC2_Repo#133]
John and the PhoSim team are discussing with Camera and DM experts the issue we discussed on the orientation convention and pre-scan issues etc.  I wanted to  track the issue that exists in the PhoSim repository here also.  It is here:

https://bitbucket.org/phosim/phosim_release/issues/37/electronic-orientation

They are discussing the best approach to make the conventions match.  Until this is finally addressed we may need a fork of obs_lsstsim for PhoSim processing as discussed in the last DC2 video meeting.

This issue serves as a place holder here to let us know if the issue has been resolved yet or if we need to also address it in the DC2 code base.  We can close this when the associated issue closes.

**Comment by katrinheitmann** [comment]
My understanding is from the bitbucket discussion above this was resolved and is now formally released in v3.7.9. So I close this issue (@cwwalter if I am missing something, feel free to reopen).
