### ISSUE TITLE
Number of visits for Run 1.1

### ISSUE THREAD

**Issue by TomGlanzman** [LSSTDESC/DC2_Repo#134]
The visit lists for each wavelength band and survey field were generated by @rbiswas4.  They represent 1.5x the number of visits needed to satisfy the Run 1.1 requirements *if* those visits populated the entire focal plane.  Rahul has suggested that we likely do not need to simulate all of the visits in his lists.  The number of visits currently in these lists is as follows:

Band|Survey|#Visits
-------|---------|---------
u|WFD|67
g|WFD|91
r|WFD|245
i|WFD|223
z|WFD|247
y|WFD|252
u|uDDF|192
g|uDDF|138
r|uDDF|138
i|uDDF|137
z|uDDF|136
y|uDDF|135
-|TOTAL|2001

If we do not need to simulate 100% of these visits, the number for each of the twelve combinations will be needed to limit the production.

**Comment by rbiswas4** [comment]
To clarify the issue a little:
In the specifications document @drphilmarshall had computed the number of run 1.1 visits for wfd and uddf, assuming these were full focal plane visits with 189 sensors. Since the uDDF and Main Survey regions will be visited by pointings that partially observe sky areas outside those being simulated, the number of sensors that will be simulated per visit is generically <= 189. We had discussed how to address the possibility that at 786 wFD visits the number of sensors simulated could be << 189 * 786, and had initially agreed with Jim to bump up the number by 25 percent (and subsequently), and believed that the production code would only simulate a fixed number of sensors.   It seems that this might not be the mode we will run in, and so we are keeping the original estimate before bumping up the numbers of visits. 

I calculated these in a branch (https://github.com/LSSTDESC/DC2_Repo/tree/Issue134/smaller_visitlist) which should *NOT* be merged, and hence I did not issue a PR. I put these files on `/global/projecta/projectdirs/lsst/groups/SSim/DC2/shorter_visitlist`.

**Comment by rbiswas4** [comment]
And we can also get the number of visits for each file from the list (ie. for example if we take the 58 lines of the  protoDC2_visits_WFD_g-band.txt in the master branch of this repo in the directory `data/Run1.1`  we will produce the added files:
```wc -l *.txt
   58 protoDC2_visits_WFD_g-band.txt
  140 protoDC2_visits_WFD_i-band.txt
  131 protoDC2_visits_WFD_r-band.txt
   43 protoDC2_visits_WFD_u-band.txt
  181 protoDC2_visits_WFD_y-band.txt
  197 protoDC2_visits_WFD_z-band.txt
   95 protoDC2_visits_uDDF_g-band.txt
   95 protoDC2_visits_uDDF_i-band.txt
   95 protoDC2_visits_uDDF_r-band.txt
  113 protoDC2_visits_uDDF_u-band.txt
   94 protoDC2_visits_uDDF_y-band.txt
   95 protoDC2_visits_uDDF_z-band.txt
 1337 total
```

**Comment by TomGlanzman** [comment]
A remaining question is whether we *should* reduce the number of visits to @rbiswas4 's smaller numbers above.  As production on the WFD r-band (nominally 245 visits) has already started, I am thinking to go ahead with the original numbers unless others agree that the smaller number of visits is adequate - attention please: @jchiang87 @salmanhabib @katrinheitmann

**Comment by salmanhabib** [comment]
@TomGlanzman Better to stick with the original numbers for now, we can always reduce later if there are any issues, right?

**Comment by katrinheitmann** [comment]
Is this in the end now just a question of compute resources? If that is the only concern, I would keep it as is. If there is some other reason, I am not sure I am understanding it fully... @rbiswas4?

**Comment by jchiang87** [comment]
@drphilmarshall's original proposal for Run1.1p was to devote 3 days of running wall clock time to this run (hence his question in the #desc-dc2 channel about starting the clock) and to do as much as can fit into that time frame.  Unfortunately, this leaves open the question of how to distribute that time over the 12 visit lists given that we may not be able to do all of the proposed visits.  I would recommend launching a similar number of visits in for the other 11 visit lists before going back to WFD r-band.  Beyond that, I don't have any other concrete recommendation.

**Comment by rbiswas4** [comment]
@katrinheitmann It is about the fact that the longer list might exceed compute resources planned on and the shorter list might end early (and use too less) on account of part of the focal plane not being simulated. 

@jchiang87 's message addresses why the clock might not work (@jchiang87 I think we want each of the main survey and the uDDF to proceed in order of MJD if that helps) . I  will be happy to provide subsets of different kinds if that can help!

**Comment by TomGlanzman** [comment]
I had already submitted 245 WFD r-band visits so propose letting them go to completion.  But then I will follow up Jim's idea with some number of the remaining 11 configurations.

The "three days" represented 500 nodes (IIRC) running flat out.  But I reminded Phil about ramp-up and ramp-down, and that things seldom worked as desired due to operational hiccups, so one should really multiply those three days by a factor of 2-3 (?).  The result was 3 days -> 3 weeks clock time.

**Comment by rbiswas4** [comment]
@TomGlanzman Would we be getting to know the number of sensors simulated as a function of time (and stop it at 131 * 189) or only at the end of the 245 visit job ?

**Comment by TomGlanzman** [comment]
@rbiswas4  For r-band, we will learn the execution time distribution from the [workflow plots](http://srs.slac.stanford.edu/Pipeline-II/exp/LSST-DESC/P2stats.jsp?task=49891001&startTime=&endTime=&p2hours=&filter=Submit&process=49891003#ProcessTabs).  Statistics will improve as more sensors are simulated.  From past experience, there may be observable variation in execution time between the bands.  To estimate throughput, one then decides how many nodes/cores will be running in parallel.  My plan is to ramp up until something breaks or the job is done, so won't know actual throughput until the task is complete (which will include all operational inefficiencies).

**Comment by katrinheitmann** [comment]
Hmmm .... 3*2=6 or 3*3=9 and not 21, right? ;-)

If 25 sq degrees really will take 3 weeks, that would mean 300 sq = 30+ 
weeks so it would take as more than half a year for full DC2? Or if we 
increase to 1000 nodes it would be still ~4 months?

**Comment by salmanhabib** [comment]
How could the preliminary calculations be so off? Are the waiting times at NERSC much worse than expected?

**Comment by rbiswas4** [comment]
@TomGlanzman Thanks!
I guess what I am wondering is if the workflow does the jobs visit by visit, then if we can keep tabs on the total number of sensors simulated, we should be able to stop the job when the number of simulated sensors is ~ 189 * 131 (which is what we had desired from Phil's initial estimate)? Now of course, stopping at that stage would make sense only if we are not charged for the jobs it does not do on termination. 

If the answer to these is yes (which I am far from sure on), then I think we have a way of simulating the original numbers of sensors we wanted with your current methodology.

**Comment by TomGlanzman** [comment]
@rbiswas4 The sensors are not necessarily simulated in an exact order.  The submission order is fixed (order determined by the visit list), but due to rollbacks, pilot life cycles, etc., the individual sensor jobs get mixed up.  Thus, even monitoring the total number of sensors, that would not guarantee "complete" visits.

@katrinheitmann and @salmanhabib For Run 2.0 there should (hopefully) be very few ramp-up/ramp-down cycles (min one, but also one additional for each cori outage during the project).  The extra factor of 2-3 for the "3-day" run is just my conservative way to avoid prepare for the worst.  Remember also that this is our first experience with the current mix of phosim version, instanceCatalog generation and other configurations so we will should have a more reliable performance metric once Run 1.1 completes.

**Comment by rbiswas4** [comment]
@TomGlanzman I see ... yes, I guess the approach I was considering will not work as I was thinking. Thanks!

**Comment by katrinheitmann** [comment]
@rbiswas4 I suppose this can be closed? Thanks!

**Comment by katrinheitmann** [comment]
I am closing this now since Run 1.1 is long done. If needed, feel free to reopen.
