### ISSUE TITLE
Baseline PhoSim background run

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/DC2_Repo#141]
At today's [CI meeting](https://docs.google.com/document/d/18i5eDgYB8HUyth80_gHekpCBu7nDOfCi97nWbLCB5js/edit#bookmark=id.l2xlpbjvs7is), it was proposed to run a simulation dataset to provide a baseline assessment of the sky backgrounds in phosim.  These simulations should use the Run1.1 visits with the following configurations
* Use settings `airglowvariation 0` and `clearclouds` to suppress intended sky background variations
* Disable `quickbackground` optimization
* Only simulate sensor-visits that contribute to a raft-sized patch of the sky.
We'll need a new script to down-select those sensor visits.

**Comment by katrinheitmann** [comment]
So I am confused about this (and this is mostly my theorist's ignorance) -- we do have test 00009 that satisfies your first two bullets. What would we learn if we extend the test to a raft-sized patch of the sky that we cannot learn from this small test? Wouldn't it be more important to first establish the metrics that tell us the PhoSim run is satisfactory for what we want to do, try those out on the small tests and then scale up? Thanks!

**Comment by salmanhabib** [comment]
Test 9 is raft-sized.

**Comment by katrinheitmann** [comment]
So then what is the difference between the new proposal and test 9???

**Comment by katrinheitmann** [comment]
We have this test (27/28) so I am closing this for now. If we need a bigger test, we can reopen this later.
