### ISSUE TITLE
Verify zeroed entries in x-talk input matrix

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/DC2_Repo#143]
Hi John(@johnrpeterson), 

I was looking at the matrix in segmentation.txt that sets the x-talk parameters after @boutigny and all were trying to understand the recent DC2 data.

Here is an extracted version for a sensor (they are all the same) from the segmentation.txt version in phosim_release:

<img width="969" alt="screen shot 2018-03-17 at 3 56 56 pm" src="https://user-images.githubusercontent.com/5562740/37559401-e9c91104-29fb-11e8-9782-64dadbe7d250.png">

Is it possible there was some sort of data copying error especially for row 1 where we see all of the zeros? Perhaps they were accidentally zeroed out? Or does the current data source for the input have this feature?

Also, for future reference: Here is some information from Adam Synder (can't find GH name) and @aaronroodman about the latest xtalk measurements from our sensors on RTM-005 in his talk at this SAWG meeting: https://confluence.slac.stanford.edu/display/LSSTDESC/SAWG+meeting+SLAC+Feb+2018  (See especially Pg 5) reproduced here:

<img width="721" alt="screen shot 2018-03-17 at 4 09 46 pm" src="https://user-images.githubusercontent.com/5562740/37559483-a333b738-29fd-11e8-9a1e-27633f7b99d8.png">

Adam can supple a multi-extension datacube, with the first image as the xtalk matrix if it is useful.

Thanks!

**Comment by johnrpeterson** [comment]
i checked and the original data had zeros in various places, including most of that one row.  so it must just be elements that are hard to measure and are close to negligible.

**Comment by cwwalter** [comment]
> i checked and the original data had zeros in various places, including most of that one row. so it must just be elements that are hard to measure and are close to negligible.

Thanks @johnrpeterson!  Can you clarify for us where the original data came from and what kind of sensors they were?

Also, what procedure should we follow to get the new data from @aaronroodman and Adam (see above) integrated into the released files?

**Comment by johnrpeterson** [comment]
what's there is lsst sensors already.

**Comment by RobertLuptonTheGood** [comment]
> what's there is lsst sensors already.
I don't understand.  The numbers that Chris pointed you at are the project's current best estimate for some chip at SLAC;  I think we should use them rather than some older numbers that you got from somewhere.

**Comment by johnrpeterson** [comment]
the numbers are another project's estimate too.  i'll ask what to use.

**Comment by cwwalter** [comment]
I am going to close this.  We are seperatly discussing with @smr456 and the camera team how to get project blessed values for xtalk/noise etc for use in the final DC2.
