### ISSUE TITLE
Lens shape parameters differ depending on filter in PhoSim

### ISSUE THREAD

**Issue by danielsf** [LSSTDESC/DC2_Repo#149]
@ksk and I were investigating the difference between the optical model encoded in `obs_lsstSim` and the actual refraction as modeled by PhoSim.  To do this, we generated InstanceCatalogs with sources at known positions on the focal plane (at least, according to the transformation methods in `obs_lsstSim`), ran those InstanceCatalogs through PhoSim with the following configs
```
clearclouds
backgroundmode 0
cameraconfig 7
opticsonlymode 1
centroidfile 1
rotationjitter 0.0
elevationjitter 0.0
azimuthjitter 0.0
perturbationmode 1
```
and compared the positions of the sources in the resulting centroid files with the predicted positions.  As expected, we found that `obs_lsstSim` did not perfectly account for refraction through the telescope.  What we did not expect was that there was a strong filter-dependence in the displacement between the predicted and realized positions.  All filters show a displacement that grows as you get farther from the center of the field of view.  In r band, the difference between predicted and realized position has min, median and max of
```
min_r = 1.39*10**-4 mm
med_r = 0.0714 mm
max_r = 0.119 mm
```
in u-band, the same stats are
```
min_u = 1.06*10**-3 mm
med_u = 0.247 mm
max_u = 0.394 mm
```
Other bands also have unqiue values for the above metrics.

Without doing too much digging, it appears that this difference is related to the fact that the files specifying the shapes and positions of the optical elements of the telescope differ as a function of band.  These files can be found in `$PHOSIM_DIR/data/lsst/`.  Looking at `optics_0.txt`, we see that L1 has thickness of 3.57 mm, L3 has a thickness of 42.4 mm, and FE (which I think is the gap between the filter and L3) is 26.6 mm wide.  Looking at `optics_2.txt`, we see that L1 has a thickness of 0.77 mm, L3 has a thickness of 51.1 mm and FE is 17.9 mm wide.  If we hack `optics_0.txt` to agree with `optics_2.txt`, we get good agreement between the u band and the r band in our "predicted-vs-realized location" test.

Do we expect these physical parameters to vary with filter changes?

(note: I am using version 3.7.9 of PhoSim)

@johnrpeterson

**Comment by jmeyers314** [comment]
I'm sure @johnrpeterson can say more, but I think I happen to know at least part of what's going on here.

I believe the thickness columns in each row of the optics files indicate the distance of the current surface from the preceding surface.  So the 3.57mm you quoted above isn't the thickness of the L1 glass (which is actually 82.23mm), but rather is a filter-dependent best-focus offset.  Similarly, while the glass thickness of the actual filters does vary, and also the distance between the trailing filter surface and L3, L3 itself isn't varying.

I also happened to already have some code available to use [batoid](https://github.com/jmeyers314/batoid) to compute transformations between field angle and focal plane position, so I went ahead and looked at this for the different filter configurations of the unperturbed telescope.  The following plot shows the Jacobian of that transformation in the radial and tangential directions for each filter:

![unknown](https://user-images.githubusercontent.com/3650485/38473006-524b3c1e-3b3d-11e8-891f-552b9e5dec91.png)
So the radial difference between u-band and r-band looks like about 0.015 cm / deg, which if we assume a typical radius of ~1 degree makes 0.15mm, and isn't so far from the difference between, e.g., med_r and med_u you quote above.

-Josh

**Comment by danielsf** [comment]
Thanks @jmeyers314 

Using your interpretation of column (3) of the `optics_*txt` files (distance of a surface from a previous surface), it looks like the variation in the `L3` parameter is such that the distance between the front of the filter and the front of L3 is always 69 mm (the distance between the front of the filter and L3 being the sum of the `FE` and `L3` parameters).  The variation of the `L1` parameter, then, is the change denoting actual motion, since it looks like it means that the distance between the front of the camera and M1M3 is going to change depending on what filter we are using to observe.  This sounds to me like a reasonable behavior for our active optics system.  I just want to give the experts a chance to chime in: do we expect the camera to be moving a few mm relative to the mirror depending on what filter is in place?

**Comment by danielsf** [comment]
Consulting

https://docushare.lsstcorp.org/docushare/dsweb/Get/Publication-34/

it sounds like we do expect the camera position to change by millimeters.  Nothing seems to be amiss.  Sorry for the noise.
