### ISSUE TITLE
Integrate protoDC2 into DESCQA-2

### ISSUE THREAD

**Issue by katrinheitmann** [LSSTDESC/DC2_Repo#15]
integrate the protoDC2 catalog into DESCQA-2

**Comment by yymao** [comment]
The reader for proto-dc2 is basically done, so once #8 is resolved this one will be almost done too.

**Comment by yymao** [comment]
This is done (See https://github.com/LSSTDESC/gcr-catalogs/pull/7). Thanks to @dkorytov. 
(Can someone who has permission close this issue?)
