### ISSUE TITLE
Rename color-color locus and clean up for tutorial

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/DC2_Repo#178]
Rename the color-color stellar locus notebook and clean up in preparation for use in a tutorial.

**Comment by wmwv** [comment]
Some of this is already being done on
u/yymao/remove-readers-and-update-notebooks

**Comment by yymao** [comment]
Feel free to push to `u/yymao/remove-readers-and-update-notebooks` (i.e., #177) if you'd like to clean up the notebook. I suspect that we will continue to update the notebooks as @djperrefort updates the reader.

**Comment by yymao** [comment]
Closing this now. If we still want to further rename the notebooks, we should probably open another issue (and this time it'll be more involved, as we need to update all links that link to these notebooks.)
