### ISSUE TITLE
Add PSF model extraction to Postage Stamp Notebook

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/DC2_Repo#181]
Show how to extract the PSF model in a postage sample.

Discuss both:
1. Full PSF model.  How to use, and how to realize at a given point.
2. Catalog saved moments of the PSF at the location of the given object.

**Comment by yymao** [comment]
This is done!

**Comment by RobertLuptonTheGood** [comment]
I haven't looked at the PSF examples, but if you're subtracting the PSF model with something like
    psfIm = exposure.getPsf(s.getCentroid()).computeImage()
    psfIm *= s.getPsfFlux()
    exposure.maskedImage[psfIm.getBBox()] -= psfIm
you will need to correct the psfFlux for the aperture correction.  I've been burnt by this in my time!

**Comment by wmwv** [comment]
Yeah, that's why I wanted to do this intentionally too simplistically.  I didn't want to go down the road of including the aperture correction.  There is also nothing in this Notebook yet about loading the coadd catalog.

But perhaps this isn't obviously overly simplistic to the new user and that in the future we should add going all the way through.

Created #222 to capture.
