### ISSUE TITLE
Clean up tutorial notebooks for DRP

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/DC2_Repo#186]
Review Jim's notebooks for access the DRP using butler. Make sure they are tutorial-ready, sit inside this repo and are organized. We will also add more notebooks that cover similar topics as in #185 but using butler.

**Comment by jchiang87** [comment]
I added three notebooks to the [`u/jchiang/cmu_tutorials`](https://github.com/LSSTDESC/DC2_Repo/tree/u/jchiang/cmu_tutorials/Notebooks) branch:

1. [Plotting_the_protoDC2_skymap](https://github.com/LSSTDESC/DC2_Repo/blob/u/jchiang/cmu_tutorials/Notebooks/Plotting_the_protoDC2_skymap.ipynb)
2. [LSST_Stack_matching_code](https://github.com/LSSTDESC/DC2_Repo/blob/u/jchiang/cmu_tutorials/Notebooks/LSST_Stack_matching_code.ipynb)
3. [DC2_Coadd_Run1.1p_Butler_Access_HSC_selection](https://github.com/LSSTDESC/DC2_Repo/blob/u/jchiang/cmu_tutorials/Notebooks/DC2_Coadd_Run1.1p_Butler_Access_HSC_selection.ipynb)

If these look like what we want for the tutorials, I'll add commentary, references, etc..

**Comment by yymao** [comment]
Looping in @EiffL for checking the contents. It looks good to me. But for the second and the third notebooks, I do wonder what would be our tone be in terms of recommending people what methods to use. Both of the two use cases (2 and 3) seem better to use the coadd (and truth, for 2) catalog(s). 

Also, maybe rename the first notebook? The title sounds like it's accessing the extragalactic catalog but it's actually not. 

The other thing that @wmwv noticed in another thread is that we should use `desc-stack` as the kernel so that people don't need to choose kernel if they follow the instructions. (cc @heather999).

**Comment by jchiang87** [comment]
I'll rename the first one to be `Plotting_the_Run1.1p_skymap`.   For the second notebook, my main goal was to show how visit-level `src` catalogs could be used the same ways as the `coadd` catalogs.  However, a secondary goal was to show how one could check the astrometry and photometry of the visit level data, since it's unlikely those data will ever be available via any other means than by using the butler.  If we have a truth catalog available by the meeting, I reckon I'd switch to that instead of just using the proto-dc2 v2.1.2 galaxy catalog.

**Comment by wmwv** [comment]
1. The first one is good.  It shows basics of accessing the Butler, but in a simple way and then ends in a visual that is key to people understanding tract, patch, overlap etc. in Run 1.1. 

2. I found the rotation stuff in the second notebook really confusing.  I think I really don't want to know why I need to know that.  People have explained this to me several times, and I know what nutation, precession, refraction and abberation are but I still don't understand why we have to go through all this gymnastics to talk about RA and Dec in the catalogs.

3. We should integrate the third with a discussion and showing the equivalent code in `DC2_Repo/scripts/merge_tract_cat.py` does. 

More thoughts later

**Comment by jchiang87** [comment]
The rotation stuff is problematic.  One should be able to import that `FieldRotator` class from the `sims_GCRCatSimInterface` package, where it lives and thereby mostly avoid highlighting it, but there is an issue with some package that `sims_GCRCatSimInterface` imports that breaks matplotlib (something about the QtAgg backend).  Let me see if I can sort that out (I tried before, but failed)...if I can't then I would just add a comment that the rotation code should just be importable from `sims_GCRCatSimInterface`.

**Comment by jchiang87** [comment]
BTW, once the truth catalog is available, all of that field rotation code isn't needed and so should be omitted entirely.

**Comment by drphilmarshall** [comment]
As a new NERSC user (!) I was able to run all three notebooks out of the box, no problem :-) I cleared the outputs, and noted Jim's renaming. He tells me he'll start a PR later on, once he's made a start at the markdown cells - I asked him to assign me and @awborgland as reviewers, as your guinea pig NERSC/DC2 newbies :-)

**Comment by yymao** [comment]
These notebooks have been cleaned up and are now being reviewed.
