### ISSUE TITLE
Simple manual CIT and output deployment for tutorial notebooks

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/DC2_Repo#188]
This is something I started doing over in the stack club, and I think we need it here too: a script that runs all our notebooks, makes static html pages out of them, and deploys them to an orphan branch so that they can be viewed, with plots (while the notebooks remain lightweight and easily diffed). I'll copy over the [relevant script](https://github.com/lsst-com/notebooks/blob/master/beavis-ci.csh) and see if I can make it work.

**Comment by cwwalter** [comment]
Instead of making html pages, why not just run them and then point http://nbviewer.jupyter.org at them from a page?

**Comment by drphilmarshall** [comment]
The thing to avoid is committing the outputs - they can make the repo get big quite quickly.

**Comment by drphilmarshall** [comment]
The other reason for not committing outputs is that they make the notebooks harder to git merge - so you get more conflicts with multiple developers.

**Comment by cwwalter** [comment]
Right.. I was suggesting just copying to the orphan branch instead of writing HTML to the orphan branch. I figured the output would be the same in any case. Is the point that the HTML output is actually quite a bit smaller even with the output?

**Comment by drphilmarshall** [comment]
I think they are probably similar. While you were replying I implemented the html scheme, check out the links from a partially upgraded Notebooks README [here](https://github.com/LSSTDESC/DC2_Repo/blob/u/jchiang/cmu_tutorials/Notebooks/README.md). We can switch to making notebook-format output and using nbviewer if this doesn't suit. I'm working in Jim's `u/jchiang/cmu_tutorials` branch, BTW, so his PR will contain a review-able script.

**Comment by cwwalter** [comment]
I think the link to the ipynb file on the page might not be write.  I get a 404 and I see two "notebooks" in the path.

**Comment by drphilmarshall** [comment]
Oh, well caught - I fixed the Notebooks/Notebooks bug in the issue/188/clean branch, [here](https://github.com/LSSTDESC/DC2_Repo/blob/issue/188/clean/Notebooks/README.md). PR #200 awaits your review, @cwwalter - I switched to making notebooks with outputs and using nbviewer, as you suggested, I think this is nicer than the plain html I was making. Thanks!
