### ISSUE TITLE
validation of DC2 galaxy bias model with DESCQA

### ISSUE THREAD

**Issue by rmandelb** [LSSTDESC/DC2_Repo#20]
@yymao - Please correct me if I am wrong, but I believe you implemented some of the correlation function-related tests that are in DESCQA.  Is that right?

The reason I'm asking is that for DC2, we have been reviewing the analysis working group requests, and there is interest from multiple groups in confirming that the galaxy bias (a) has reasonable scalings with luminosity, and (b) is decently complicated / nonlinear on the scales we expect nonlinear bias to be relevant.

It seems to me that this could be confirmed with a reworking of existing tests in DESCQA, e.g., constructing a scale-dependent bias from a ratio of galaxy and matter power spectra or 3d correlation functions, and doing this in a few luminosity bins to confirm the luminosity scalings.  How challenging would this be to implement for our tests on the proto-DC2 catalog so we can go back to these groups with a statement about how the galaxy population from the SAM fulfills their requests?

**Comment by yymao** [comment]
@rmandelb I did provide the wp(rp) code in DESCQA v1, but the code only works under the thin-plane approximation, and it doesn't calculate the bias. We need code to do this for the light-cone catalogs but I don't have existing code yet.

**Comment by rmandelb** [comment]
@yymao - sorry for the ignorant question, but is the SAM applied directly to the light cones?  i.e. is the ordering N-body sim snapshot -> light-cone -> SAM -> galaxy catalog?  Or is it N-body sim snapshot -> SAM -> light-cone?  If the former, then yes we definitely need code to calculate the galaxy and matter clustering statistics on the lightcone and infer the bias.  If the latter, then it's probably safe enough to do this test within the snapshots using the existing code.

**Comment by yymao** [comment]
@rmandelb I think SAM is applied on the snapshots before the light cone is created. So you're right; however, the snapshots for proto-dc2 have not been made available.

**Comment by katrinheitmann** [comment]
Yes, that's correct (first snapshots, then lightcones). My understanding 
was that there was not much interest in the snapshots, we could make 
those available if it's useful.

**Comment by rmandelb** [comment]
@katrinheitmann - interesting - I had remembered hearing a request for at least some snapshots, but couldn't find it on our spreadsheet.  It seems it was a request from the clusters WG that didn't make it onto the spreadsheet (every one of their other requests did though, we just missed that one).  I just added it at the bottom.

Of course, if only one group has requested this then it's not clear it's worth a lot of effort.  In this case, I was recommending the use of snapshots because I thought it would make things easier (i.e., because they let us reuse existing code in DESCQA).

So, thinking this over, does it mean that we either need (a) additional effort to make snapshots available or (b) additional effort to update DESCQA tests to handle light cones?  (we could use treecorr or some other fast tree code to do a fast correlation function calculation in the light cone)  I guess (b) is functionality that we'd want in DESCQA anyway, so may as well do that and bypass doing the validation tests on the snapshots?

Should we ask the LSS group if they have a volunteer to implement this test?

**Comment by katrinheitmann** [comment]
@yymao and Eve should chime in about the snapshot handling in DESCQA2, but one major feature of DESCQA2 is that it can handle lightcones. At some point, we had a switch in the reader (lightcone/snapshot) but I am not 100% certain that it was carried over into DESCQA2. There is really no additional effort in making the snapshots available (besides at some point maybe disk space).

**Comment by evevkovacs** [comment]
The readers can handle either snapshots or lightcones. The specification 
for the type of catalog is listed in the catalog metadata, and the reader 
reads that in first. The tests to date have been written for snapshots, 
but several of them will already work on light-done data too.
For correlation functions, we have the option of using pre-existing code 
such as Mike Jarvis' code (treecor I think) or a module from HaloTools.
I've been talking with Andrew Hearin about the latter and will take a look 
at it after protoDC2 production is done. I think all of these issues are 
under control. It's just that we are too busy with more urgent tasks, such 
as meeting the protoDC2 dealine, to make much progress at the moment.

**Comment by rmandelb** [comment]
Fair enough.  As long as this is on the radar and there is a plan, it's fine!

**Comment by katrinheitmann** [comment]
Closing this issue now since it is taken care of in descqa repo: https://github.com/LSSTDESC/descqa/issues/10
