### ISSUE TITLE
Review of FoFCatalogMatching Histogram.ipynb

### ISSUE THREAD

**Issue by djperrefort** [LSSTDESC/DC2_Repo#211]
Overall I found the notebook easy to follow. I only have a few minor comments:

1. Listing the learning objectives at the beginning is a great idea.
1. The description of the `return_iterator` kwarg makes it sound like an option intended for compatibility with matplotlib. A minor semantic concern.
1. Including a link at the top of the document pointing to a general overview of the GCR would address potential user questions like "What is a native vs non-native quantity?".
1. Typo in the 15th cell "tha" -> "the"
1. When using the `FoFCatalogMatching.match` method it's not immediately clear what each of the specified arguments accomplishes. You could leave it to the user to call `help` but a brief comment would be helpful.
1. The last few cells where you find the `one_to_one_group_mask` and calculate `delta_arcsec` could use some description on what you are trying to do.

**Comment by yymao** [comment]
Thanks @djperrefort, I am working on fixing this.
