### ISSUE TITLE
Review of Lensing Cuts.ipynb

### ISSUE THREAD

**Issue by chihway** [LSSTDESC/DC2_Repo#216]
This issue is to track feedback on the notebook [Lensing Cuts.ipynb](https://github.com/LSSTDESC/DC2_Repo/blob/master/Notebooks/DC2%20Coadd%20Run1.1p%20GCR%20tutorial%20--%20Part%20II:%20Lensing%20Cuts.ipynb). It runs through smoothly, only very minor suggestions:

* maybe point out that this one is run under desc-stack environment (look at the upper right corner for the kernel) because it needs to interact with the butler
* last plot: maybe overlay the before- and after-cut histograms?

This is super cool, btw!

**Comment by rmandelb** [comment]
On a super minor note, just to avoid confusion with how these are referenced elsewhere, I recommend upgrading the references to Bosch et al (2017) and Mandelbaum et al (2017) so they say 2018, and point to
http://adsabs.harvard.edu/abs/2018PASJ...70S...5B
http://adsabs.harvard.edu/abs/2018PASJ...70S..25M

Also for HSC DR1, maybe in the first instance, refer to Aihara et al (2018) for more detail: http://adsabs.harvard.edu/abs/2018PASJ...70S...8A

**Comment by chihway** [comment]
Looks good, thanks @fjaviersanchez !

**Comment by yymao** [comment]
fixed by #219
