### ISSUE TITLE
timeline for DC2 production

### ISSUE THREAD

**Issue by katrinheitmann** [LSSTDESC/DC2_Repo#24]
- add dates for freezing of specific tools (galacticus, phosim, imsim) to timeline diagram
- make timeline diagram in google slides (currently png in google slides) so that it can be easily changed (https://docs.google.com/presentation/d/1yUBsDtHAqGh30W8RrGuprqFQDZaDVqnTXwOiX3BULYA/edit#slide=id.g25be2ee806_0_0)

**Comment by katrinheitmann** [comment]
As promised a while ago, I finally got around to put the timeline diagram into google slides so that everybody can add and edit the timeline. One addition requested by Rachel: dates for code freezes (so by that date, we really do not want to add any more new features). The timeline is aggressive (in particular given all the holidays in Nov./Dec.) but I think it makes sense if we stick to the plan that by May 2017 we want DC2 to be delivered. I do have a good idea about how long the CS work will take (if we get enough help with the validation). After that is done, I have 1 month for CI/SSim to set things up and 2-3 months for running everything (or less time for setting up and more time for running). In this diagram, all ImSim/PhoSim work will need to be finalized and verified by the SLAC collaboration meeting in Feb. Anyway, take a look at let me know if this is crazy. If not, we can start populate the repo with more deadlines and issues ...

**Comment by katrinheitmann** [comment]
I have tried to fill in as much of Section 8 in the planning document as possible. Please take a look and in particular @jchiang87 if you can see if the timelines for the image and DM part make sense? 
To everybody else: you should decide about the phosim/imsim use and what you want to add about that in the timeline (there is a separate section 5 about those two tools in general, so I think in the timeline section we want to keep it short but maybe want to say what we want to use). I can also see that we will decide this after the downscaled version is finished, which we can then just write  in there as well.

**Comment by cwwalter** [comment]
Hi Katrin,

Is there a difference between pages 2 and 3 in those timeline slides?  It's not obvious to me what different aspect they are suppose to show yet.

**Comment by katrinheitmann** [comment]
Page 2 is made inside google slide so you can move things around and 
change things. It also has the CI/SSim and CS Freeze points. It's the 
latest version. Slide 3 was the original png file which you would not 
have been able to change (besides adding comments). I kept slide 3 there 
in case somebody does make changes to Slide 2 and we want to take a look 
at the original again. We can move it to the end.

**Comment by katrinheitmann** [comment]
If there are no more comments on the timeline, I actually would like to close this issue. We still need to finish Section 8 in the planning document but overall, I think the timeline is basically settled.
