### ISSUE TITLE
Track DC2 calibration product testing

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/DC2_Repo#42]
This issue is to track the status and results of tests related to DC2 calibration products

To start:

@PierreAstier and @antilogus and the SAWG / technical groups (also CC: @nomerot) will test flats produced by PhoSim v3.7 with the new background options to understand their variance properties in relationship to what is needed for brighter-fatter production and correction.

At first, based on their request, they will test 5 flat pairs (of one 4kx4k CCD) , filled up to somewhere 
between 50 and 100 ke  per pixel, with the BF off to measure and characterize any residual correlation.

@TomGlanzman is working on the production of the flats.

Separate flats for flat fielding / vignetting etc may be produced later but at a lower intensity level. This first test is focused on what we need to use BF.

**Comment by TomGlanzman** [comment]
UPDATE:  All five flat pairs are now being processed at NERSC.  With a bit o'luck they might all be complete by sometime Friday (11/17).  The initial configuration looks like this:

domeint = 16
filter = 2
visitime = {19,23,26,30,33}
approx #e-/pixel = {50,60,70,80,90}k
approx production time = {33,39,46,52,59}h

Each image in all pairs has a unique random number seed.

**Comment by cwwalter** [comment]
👍 Are they running in the interactive partition the > 48 hr jobs can complete?

**Comment by TomGlanzman** [comment]
@cwwalter Three jobs are running on a single Haswell batch node (at 48 hour limit), while the other two -- longer jobs -- are being sneakily run on public login nodes.  It is my hope that they fly under the radar of the NERSC police.

**Comment by TomGlanzman** [comment]
There was a minor setback in that the three pairs of "fast" flats running in a batch machine all unexpectedly timed out (but for one) after 48 hours.  So I restarted these manually on login nodes yesterday.  There are five images left to complete.  Best guess is sometime tomorrow.  Here is a snapshot summary  (which I shall keep up-to-date):  https://docs.google.com/spreadsheets/d/1066BGvEwg_UwzHb9ZFbiUzYqY2KrGE55xqb6hnuMucM/edit?usp=sharing

**Comment by TomGlanzman** [comment]
Update: All 5 "flat" pairs (10 images) are complete per spreadsheet above.

**Comment by cwwalter** [comment]
Great!  Is it clear how the Paris people should get the output?

**Comment by cwwalter** [comment]
OK, I didn't scroll over enough.  Pierre(s) the location at NERSC is on the spreadsheet.

**Comment by cwwalter** [comment]
Good news is that @mfisherlevine has now been allocated time to get the DM BF correction working.

https://jira.lsstcorp.org/browse/DM-5082

This should hopefully be ready by the Run1.1 timescale.

**Comment by mfisherlevine** [comment]
Slightly pedantic point: "DM BF correction" is believe to already be working, and won't actually be touched by this work. What I'm going to be working on is porting the code which measures the correlation coefficients from the set of flats so that the BF corrections can be turned on for any cameras/obs_packages as long as one has flats.

**Comment by cwwalter** [comment]
Right!  Thanks for clarifying.  One other clarification: the porting is happening from code being used in HSC.

**Comment by mfisherlevine** [comment]
PS I know you know that Chris, just wanted to point out the difference in case others were confused.

**Comment by cwwalter** [comment]
These tests were done and now new work is being done. With the optimizations applied there were some problematic residual correlations.  New work is happening at ANL to try to map out the space.  A new tracking issue is probably appropriate.  I am closing this issue.
