### ISSUE TITLE
Update generateDc2InstCat.py script to produce object catalogs for imSim

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/DC2_Repo#50]

**Comment by jchiang87** [comment]
It looks like one just needs a subclass of `PhoSimDESCQA` that specifies the outputs (ICRS coordinates in particular) for imSim, i.e., similar to
https://github.com/LSSTDESC/imsim_deep_pipeline/blob/master/python/desc/imsim_deep_pipeline/catsim_utils.py#L46
@danielsf Can you confirm this please?

**Comment by danielsf** [comment]
@jchiang87 

You are correct
