### ISSUE TITLE
Check off sensor light is working properly in the pipeline

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/DC2_Repo#53]
In #5 @johnrpeterson and @egawiser discussed not making a sensor visit list to trim unwanted visits but rather trimming the instance catalog.  This was tried by @TomGlanzman and he had some issues with minsource not being respected. This might be due to the "deconstructed" phosim being used.

This is a reminder to make sure that it works.

Also the LSST-Galsim code interface needs the equivalent minsource option added (CC: @danielsf for confirmation that this doesn't currently exist).

**Comment by danielsf** [comment]
It does not currently exist

**Comment by cwwalter** [comment]
Thanks.

**Comment by cwwalter** [comment]
I believe this now exists in the imSim pipeline and there has been testing of minsource in the PhoSim pipeline too.  @jchiang87 can we close this one?
