### ISSUE TITLE
Modify instance catalogs to include images of strongly lensed transients

### ISSUE THREAD

**Issue by dannygoldstein** [LSSTDESC/DC2_Repo#60]
Subtask of #56. 

@jbkalmbach will provide code that modifies instance catalogs from CatSim to include lensed transient images from catalogs provided by @dannygoldstein.

**Comment by dannygoldstein** [comment]
CC @jchiang87 @danielsf @mpwiesner

**Comment by jbkalmbach** [comment]
Closed with Merging of LSSTDESC/sims_GCRCatSimInterface#16
