### ISSUE TITLE
Check that PhoSim e2adc output format is consistent with current devices

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/DC2_Repo#67]
It sounds like the pixel geometry some readout directions etc that were put into PhoSim in the past may not now be totally consistent with the geometry of the real devices in the test stands we have from the vendors.

@johnrpeterson Can you help us make any changes to the conventions so we can make the amplifier files for 1.1?  Do you have anything in your internal tracking system for this issue now?

@jchiang87 when you return from break can you also enter here anything you are aware of from comparing to the test stand devices?

**Comment by johnrpeterson** [comment]
there isn't any open tickets about this.  i remember fixing something in this area from @jchiang87 more than a year ago.  please open a phosim ticket, if that's not true, if there is something wrong and then i'm sure we can patch it.

**Comment by katrinheitmann** [comment]
@jchiang87 @cwwalter Is it clear now if this is an issue? If it is, have you filed a phosim ticket? If it is still not clear, who can help checking? Thanks!

**Comment by cwwalter** [comment]
@jchiang87 and @SimonKrughoff this was now changed by changing the PhoSim segmentation.txt file format right?  Could you put a link to the PhoSim issue and close this if true?  Thanks!

**Comment by jchiang87** [comment]
Here's the issue from the phosim repo where this was handled:  https://bitbucket.org/phosim/phosim_release/issues/37/electronic-orientation
