### ISSUE TITLE
intrinsic alignments

### ISSUE THREAD

**Issue by rmandelb** [LSSTDESC/DC2_Repo#7]
After our telecon last week we tasked me with consulting the relevant experts on intrinsic alignments models to go into catalog-level simulations.  This includes:

- what model(s) are of interest? (for which software would be available soon)
- what DM halo information would those methods need?  Currently halo catalogs *do not* have shapes.
- confirm that catalog-level inclusion of IA (not in images) is OK, as that means they could be added later

**Comment by EiffL** [comment]
@katrinheitmann @evevkovacs @yymao  Linked to the discussion in issue #20 , all the models that were mentioned in this week's TJP telecon to put IA in the simulations will require access to the snapshot catalogs, so there is definitely interest here in having access to them. One snapshot would be enough to get us started.

**Comment by evevkovacs** [comment]
Do you have a preferred redshift or range of redshifts?

**Comment by EiffL** [comment]
I'm asking around but the data I have readily available for this comes from the z=0.06 snapshot in MBII, so just like in the first round of DESCQA

**Comment by katrinheitmann** [comment]
We have 0.05, close enough?

**Comment by evevkovacs** [comment]
Patricia Larsen, our postdoc who is working on the halo-shape code, will be asking some more questions
about your other requirements, so that we make sure we are providing the information that you need.

**Comment by EiffL** [comment]
Yes, 0.05 is certainly close enough, at least for me, happy to chat with Patricia about the content of the catalog.

**Comment by EiffL** [comment]
After discussion, it would also be good for testing to have a higher redshift snapshot, like around z=1 in addition to the low redshift snapshot. This also sounds like what was asked in #27

**Comment by evevkovacs** [comment]
So, to summarize, both clusters and IA would like 2 snapshot catalogues, one at z~0.9 and one at low redshift. Two suggestions for the lower redshift values are 0.05 and z~0.2. I see no reason that we couldn't provide catalogues for all 3 values.

**Comment by katrinheitmann** [comment]
ok, (thanks to everybody for sorting this out, in particular Patricia and Francois!) the following items are listed in the DC2 planning document (some of them were there already):
 galaxy:
       - positions
       - luminosities
       - SFR
     - bulge-to-disk ratios
      - is_central flag
Halos:
       - shape eigenvectors
      - masses
       - angular momenta
Particles 
        - density field
In addition I added a note that for testing purposes there will be two snapshots for protoDC2 delivered at z~0.05 and z~0.9.

Since the models themselves are discussed in another issue, I think we can close this one.
