### ISSUE TITLE
Where is the uDDF going to be?

### ISSUE THREAD

**Issue by dannygoldstein** [LSSTDESC/DC2_Repo#71]
@cwwalter @drphilmarshall 

Where on the sky is the uDDF going to be in DC2? Asking because this affects which protoDC2 galaxies can be used in the sprinkler.

**Comment by cwwalter** [comment]
@dannygoldstein Just before our DC2 meeting @drphilmarshall put in "Offset but just including the Extended Chandra Deep Field South Deep Drilling Field" for the location. I understood that was after discussion with you :).  In this case offset means on the edge of that field.

**Comment by dannygoldstein** [comment]
@cwwalter @rbiswas4 @drphilmarshall

I was off the grid when this was decided and was unable to participate in the conversation. I have no issues with the Chandra location, but what I actually need is an RA/DEC footprint of the corners of the  rafts that will have DIA run on them in DC2.

Danny Goldstein
http://astro.berkeley.edu/~dgold
________________________________

**Comment by cwwalter** [comment]
> I was off the grid when this was decided and was unable to participate in the conversation. I have no issues with the Chandra location, but what I actually need is an RA/DEC footprint of the corners of the  rafts that will have DIA run on them in DC2.

Hm... OK, I wasn't part of the discussion with Phil and Rahul.  So, I think they will have to chime in.

**Comment by rbiswas4** [comment]
@dannygoldstein The location of the Extended Chandra Deep Field South at: RA: 03h 32m 30s Dec: -28d 06m 00s. However, we don't have location of rafts yet. This will depend on the dithers (though these are known to be small). This should help for testing purposes.

**Comment by RobertLuptonTheGood** [comment]
I don't think that you should assume that the dithers are tiny (I'd guess a CCD or so), and the current plan -- which may change, is extensive angular dithers.

							R

**Comment by rbiswas4** [comment]
@RobertLuptonTheGood I should have qualified that this is specifically a Deep Drilling pointings for DC2, and not about the WFD pointings that will also make up DC2. 

We are hoping for small translational dithers but could have larger rotational dithers to avoid losing  too many observations in the region. I think we had been told to expect translational dithers ~ CCD size even for the DDF pointings, but since we are simulating 30 chips only, is it possible to reduce the dither size (not yet sure how much of an issue this is)? Or would it affect something crucially?

**Comment by RobertLuptonTheGood** [comment]
I'm worried about Moiré patterns in correlated noise with rotational dithers, but that's still just a worry (i.e. full rotational is still the nominal plan).  I'll need to get back to DESC about this at some point.

For translational dithers, for now I don't think that there's anything crucial about CCD-scale dithers.  We're not (yet) tracking spatial structures in CCD QE or the filters so I don't think that you'll get into trouble (spatial structures like scattered light in flats and poor transparency should be handled by meas_mosaic/jointcal)

**Comment by drphilmarshall** [comment]
Thanks, Robert. Closing this as I think @dannygoldstein has he coordinates he needs to get started; actually applying the dithering to the required visits will be issued separately.
