### ISSUE TITLE
DC2 Cookbook

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/DC2_Repo#73]
We have DM pipelines in the form of collections of scripts in various places: for DC2 we will need to pull these together and re-apply to the DC2 images as we make them, starting ASAP. To make sure that we are implementing the data release processing (DRP) pipeline that we want to see, we need a DC2 Cookbook to check against. 

@SimonKrughoff and I discussed this a little, and we decided we should try and write it all down in one DESC Note jupyter notebook. The reasoning is that we might then be able to make it run-nable, which could help with its development. (It's also nice how jupyter makes code blocks easy, you just use a code cell rather than a markdown cell. And GitHub does a nice job of rendering Notebooks so they can be browsed on the DC2 repo web interface.) I can start by copying in the pieces from the Twinkles cookbook ("self-plagiarism is the highest form of self-flattery" - S. Digel). Then we can look through them to check that this is what we want to do. Hope this sounds OK, @katrinheitmann !

I'll assign suitable code reviewers in time, but it'd be great if @jchiang87 @tony-johnson @nicolaschotard and @boutigny could follow along from the beginning, to make sure we are on track. All comments and suggestions welcome!

**Comment by cwwalter** [comment]
We shouldn't forget the repos and scripts that were worked out to do this for DC1. The DIA is of course new here but the static stuff is not.

**Comment by drphilmarshall** [comment]
Absolutely. I originally wrote "pieces from DC1 and Twinkles" but I couldn't find a specific DC1 cookbook recipe (markdown file). I thought the DC1 DM pipeline was derived from the Twinkles static sky recipe (that makes coadds, and objects=coaddsources), so figured that https://github.com/LSSTDESC/Twinkles/blob/master/doc/Cookbook/DM_Level2_Recipe.md would be a good place to start. The additional (or different) steps followed in the DC1 processing will then need to be captured, though - who would be best placed to add those parts?

**Comment by katrinheitmann** [comment]
Just a reminder to deliver the first DC2 cookbook version.

**Comment by heather999** [comment]
This issue was moved to LSSTDESC/ImageProcessingPipelines#15
