### ISSUE TITLE
Get some sample instance catalogs to test out the sprinkler on

### ISSUE THREAD

**Issue by dannygoldstein** [LSSTDESC/DC2_Repo#81]
@jchiang87 @jbkalmbach @drphilmarshall 

The sprinkler group is requesting some sample instance catalogs based on ProtoDC2 that we can use to test our instance catalog modification codes for Run 1.1.

Do you have any of these that you can share ASAP?

Thanks,
Danny

**Comment by yymao** [comment]
@dannygoldstein I believe this is ready (if I understand what you're asking correctly). You can get CatSim instance catalog from protoDC2. See https://github.com/LSSTDESC/sims_GCRCatSimInterface

**Comment by jchiang87** [comment]
I have some here:
`/global/cscratch1/sd/jchiang8/DC2/sims_GCRCatSimInterface_danielsf/work/with_rotation`
I set the group to `lsst` so you should have read permission.  The `phosim_*.txt` guys are for use with phosim (note the includeobj lines) and the `imsim*.txt` guys are for use with imsim.   Visit 230 is centered on the Twinkles field, and visit 1418971 is in the original protoDC2 field at RA, Dec = 0, 0.  The script that generated these is 
```
/global/homes/j/jchiang8/scratch/DC2/sims_GCRCatSimInterface_danielsf/work/run_generateInstCat.sh
```

**Comment by jchiang87** [comment]
To run that script you'll need to source this setup script:
```
/global/cscratch1/sd/jchiang8/DC2/setup.sh
```
Note that this is my development area at NERSC, so it is subject to change without notice. I'd recommend making your own.

**Comment by dannygoldstein** [comment]
Thanks Jim. @jbkalmbach Does this give you what you need? If so I will go ahead and close.

**Comment by jbkalmbach** [comment]
Yes, this is good. As long as we have a way to regenerate them that's the important part. Thanks @jchiang87
