### ISSUE TITLE
PreComputation and Storage of Transient Seds for Phosim

### ISSUE THREAD

**Issue by rbiswas4** [LSSTDESC/DC2_Repo#82]
This is one of the points that was brought up by @danielsf in #59 , but I had missed the question from @salmanhabib . So, this is to discuss this particular question separately from the other questions in #59 .

The input used by phosim are `instance_catalogs` which are catalogs of astrophysical sources during the exposure of the visit. Aside from metadata, each row of the instance catalog describes an object with the columns being properties. One of these is a string which has the absolute path to a file on disk which contains the rest frame spectrum of the object (ie. wavelength, specific flux) on a grid of wavelengths . For static objects like galaxies and stars, there is just a single spectrum for an object for all visits. However, for variables and transients the spectra are different for each visit, requiring multiple files. Each of these files has a size of ~ 36K which can be zipped to about 12K. The number of such files is the number of visits for which the object is _simulated not detected_. For each SN for example, this is ~ number of visits within a ~ 80 day period. For uDDF there are roughly ~ 20K visits or 2K per year. So, this is the total number of SN * 2* 10^2 / (3.6 * 10^2) * 36KB per visit  .

 Note, the code to create the spectra at any time, is part of catsim. But rather than loop through creation of these files and then running phosim, we have been precomputing the spectra and saving the files.

**Comment by danielsf** [comment]
When I asked @TomGlanzman about this over Slack, he said
"""
Currently, the SEDs live 'outside' the phoSim code but with a pointer from there.  Maybe what you are thinking is something like: create a (large) number of SED files which are referenced from the instance catalog, and those SEDs must be findable by phoSim.  If that sounds right, then take a look here:  /global/common/software/lsst/cori-knl-intel/phosim/v3.7.6/data/SEDs which is where the entire collection of SEDs known to phoSim reside (or are pointed to).  This is where we would need to make some additions.
"""
(I am just transcribing this and pinging him so we have the entire conversation pertaining to this issue in one place)

**Comment by TomGlanzman** [comment]
To summarize the way phoSim searches for SED files:

1. A "root" directory path is identified.  By default it is <$PHOSIM_ROOT>/data/SEDs, but may be overridden by the "--seds=<path>" command line option.

2. From there, the instanceCatalog specifies a relative path to the SED file of interest, e.g. (from a real instanceCat):

object 1134779771908 0.0298015615 -0.0416839309 28.9406893 starSED/phoSimMLT/lte034-4.5-1.0a+0.4.BT-Settl.spec.gz 0 0 0 0 0 0 point none CCM 0.103732119 3.1

-----

Thus, to weave a new set of SED files into the phosim workflow, we must figure out a way to integrate these multiple sets of SEDs together.  Here is one idea:

1. Dynamic, visit-specific SEDs are generated in $SCRATCH, say $SCRATCH/dynamic

2. A symlink directory is created in $SCRATCH containing all of the default SEDs:
$ cp -as $PHOSIM_ROOT/data/SEDs $SCRATCH/SEDs

3. Symlinks are created from $SCRATCH/SEDs/dynamic  to $SCRATCH/dynamic

4. The default SED directory is then overridden by command line option.

This is straight-forward and should be fairly quick.  My only worry is running out of inodes with potentially thousands of these symlink mirrors in $SCRATCH (each instance of the default SED directory contains ~12,000 inodes).  

And note that any currently defined subdirectory names in $PHOSIM_ROOT/data/SEDs **must not be used**.  That is the following subdirectories should be considered off-limits, as they are already defined and populated with default SED files:

agnSED/
cepheid_lc/
eb_lc/
flatSED/
galaxySED/
igm/
mflare/
microlens/
rrly_lc/
ssmSED/
starSED/

So, for example, one *could* create a new subddirectory "dynamic", then in the instanceCatalog, one might see something like this:

object 1134779771908 0.0298015615 -0.0416839309 28.9406893 dynamic/starSED/phoSimMLT/lte034-4.5-1.0a+0.4.BT-Settl.spec.gz 0 0 0 0 0 0 point none CCM 0.103732119 3.1

Can this be done?

**Comment by rbiswas4** [comment]
@TomGlanzman 

Sure I see no problem in
- [ ] Visit specific SEDS *can* be created in $SCRATCH/dynamic so that the SEDs are written to dynamic/starSED/phoSimMLT/lte034-4.5-1.0a+0.4.BT-Settl.spec.gz and written to instance catalog files. (I think it would be slower to make them gzipped, but there is no problem in doing this)
- [ ] we can symlink default SEDS to scratch directory space: `$SCRATCH/SEDs`
- [ ] we can symlink $SCRATCH/dynamic to $SCRATCH/SEDs/dynamic 

and then I suppose you want to use $SCRATCH/SEDs as the root directory in command line.

inodes: This will pile up with visits and would be a problem in later runs though I suspect that Run1.1 would be fine. But I guess in the longer term, we need to have a script that deletes these spectra after they have been used. Note, that we were following a convention of denoting visit specific spectra by obsHistIDs / mjd  and filter. This should make deletion trivial based on mjd by deleting spectra files with mjd < current mjd (if we work in increasing mjd order, which I know at times we do not do.)

**Comment by TomGlanzman** [comment]
Thanks @rbiswas4.  An important part of this is how the dynamic SEDs are referenced in the instanceCatalog - not occupying the same directory path as the static SEDs.

Do you have an idea as to the approximate average number of files that will be produced per instance catalog?

Can you estimate the approximate amount of space needed?  (Files may be gzipped or not, and the CPU time is probably not an issue.)

**Comment by TomGlanzman** [comment]
@rbiswas4 and @danielsf I will test this once the catalog generator has been updated.  Please let me know when you are ready.

**Comment by rbiswas4** [comment]
These were done and should be working in the desired way for Run 1.1
