### ISSUE TITLE
Describe updated astrometric calibration procedure

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/DC2_Repo#87]
As @jchiang87 points out in #73: 

>I've only scanned the content so far, but I note immediately that the `astrometry.net` stuff has been superseded. I think the correct procedure is captured [here](https://github.com/LSSTDESC/ImageProcessingPipelines/blob/master/bin/generate_dc_reference_catalog.py) and [here](https://github.com/LSSTDESC/ImageProcessingPipelines/blob/master/python/desc/parsl/pipeline_components/pipeline_components.py#L120)

**Comment by heather999** [comment]
This issue was moved to LSSTDESC/ImageProcessingPipelines#14
