### ISSUE TITLE
Replace stack installation instructions with sensible assumptions

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/DC2_Repo#89]
As @jchiang87 points out, installing the stack should be a separate recipe, or in our case, a brief description of the assumptions we can make about the installation of the stack that we'll be working with.

**Comment by heather999** [comment]
Are we looking for installation instructions using docker images (imported into Shifter @NERSC) and/or source installs or both?

**Comment by katrinheitmann** [comment]
@drphilmarshall Has this been resolved (or more likely moved to some other github issue)? If so, can you close it? If not, what do we need to do in order to address this? Thanks!

**Comment by drphilmarshall** [comment]
I see the relevant action item still present in the DC2 Cookbook, which has moved to 
https://github.com/LSSTDESC/ImageProcessingPipelines/blob/master/doc/DRPCookbook.rst This issue is still referred to from that Cookbook, but I trust @heather999 and @nicolaschotard will clean that up as they work on the Cookbook. Let's close this out.
