### ISSUE TITLE
Galaxy catalog creation on snapshots

### ISSUE THREAD

**Issue by katrinheitmann** [LSSTDESC/DC2_Repo#9]
Run Galacticus on AlphaQ (underlying N-body simulation) merger trees to generate one Galacticus output per time snapshot

**Comment by evevkovacs** [comment]
Completed 10/18/17.
Next step to make a list of nodeIndexes of all Galacticus galaxies with halo mass > ~ 1e11 completed on 10/20/18 and passed to next phase of catalog production (generate the corresponding core catalog).
