### ISSUE TITLE
Get DC2 science papers on the board 

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/DC2_Repo#94]
Dear @LSSTDESC/wg-conveners , 

With the DC2 Run 1.1 readiness meeting happening tomorrow (0800 PT, the live notes file is pinned to the #desc-dc2 channel in Slack), the validation effort picking up serious steam, and the collaboration meeting just around the corner, now seems like a good time for us to get your working groups' planned DC2 analysis papers onto the collaboration [paper tracking confluence page](https://confluence.slac.stanford.edu/display/LSSTDESC/Interim+LSST+DESC+Paper+Tracking). 

Can you please work in your groups to post these up - _crucially, with "lead authors" listed?_ It would be great to be able to reach out to these teams individually to talk to them about whether their needs are being met by the DC2 design. In the immediate term, I'd also like to make sure that they are fully connected to the project, via Slack and also the @LSSTDESC/dc2  GitHub team. 

Watching DC2 afficionados: if you already know that you will be leading a paper, please do check in with your working groups to get your paper onto the tracking board!

As a reminder, [here are the papers that you said your groups would write](https://docs.google.com/presentation/d/1xHtwdI3C9c1cobiDFjt4qeZB45ojHn1QSNBrg2Uzx68/edit#slide=id.p), back in July at the SBU meeting, and you can see a one-line summary of these papers in the ["science uses" section of the DC2 Plan](https://github.com/LSSTDESC/DC2_Repo/blob/master/Documents/DC2_Plan/main.tex#L255).

Meanwhile, I will try to keep up with the board by maintaining a list of DC2 Notes and papers, in the [DC2 repo Documents folder README](https://github.com/LSSTDESC/DC2_Repo/tree/master/Documents). Because this repo is public, this README provides a high-visibility advertisement for DESC work in progress. We need to point out which Notes and papers have not yet been reviewed by the collaboration, but otherwise, this list should be useful both to collaboration members and fans of the DESC data challenges worldwide :-)

Comments and questions most welcome, as usual!
Thanks very much, all,

Phil

**Comment by katrinheitmann** [comment]
@drphilmarshall Do you want to close this issue or leave it open because of the links in the message? Thanks!

**Comment by drphilmarshall** [comment]
We can close this out, now that we have 21 DC2 projects proposed (and in 7 cases, already approved) [here](https://confluence.slac.stanford.edu/display/LSSTDESC/DC2+Projects) :-) Thanks all for getting this moving. 

Also, Conveners, don't forget to keep an eye on these projects, and announce them to the Members list as your group converges on each one. And please note Katrin's request for one or two points of contact to be listed for each project, so she can get in touch with the project teams to check on their needs etc. You might like to ask your project teams who these people should be, and have them work up their project confluence pages a bit. Thanks!
