### ISSUE TITLE
Rotate protoDC2 to final field center for Run 1.1

### ISSUE THREAD

**Issue by katrinheitmann** [LSSTDESC/DC2_Repo#97]
In CatSim, rotate protoDC2 to the desired position.

**Comment by drphilmarshall** [comment]
As of #96 we now have the desired position: (55.064, -29.783) deg.

**Comment by katrinheitmann** [comment]
@danielsf Just a quick question: will the rotation be done when the sprinkler will be applied? In other words, CatSim will be run once everything is fixed and all pieces will be applied? If the rotation happens separately, maybe that should be done already (though I would guess not). Thanks!

**Comment by danielsf** [comment]
A very cartoonish sketch of how CatSim and the sprinkler work would be:

1) CatSim queries the protoDC2 catalog for required quantities

2) The sprinkler scans the results of (1) and replaces suitable galaxies with lensed systems, passing the modified results back to CatSim

3) CatSim performs additional calculations to put the results of (2) into the units that PhoSim (or ImSim) expects.

The field rotation occurs in the classes that operate during step (1), so the sprinkler should already be acting on rotated coordinates (right, @jbkalmbach?)

**Comment by jbkalmbach** [comment]
Yeah, that's right. It works on the ra, dec that are returned from the catalog query.

**Comment by katrinheitmann** [comment]
The rotation has been implemented and seems to work fine. I am closing this now.
