### ISSUE TITLE
Dithered database

### ISSUE THREAD

**Issue by katrinheitmann** [LSSTDESC/DC2_Repo#98]
Produce dithered database by Monday, 6pm ET

**Comment by jchiang87** [comment]
Could someone please provide the location at NERSC of the opsim db used by #108 ?  That location should be captured in @drphilmarshall 's Run 1.1 Specifications note and in [this config file](https://github.com/LSSTDESC/DC2_Repo/pull/120/files).

**Comment by humnaawan** [comment]
@jchiang87 its here: `/global/cscratch1/sd/rbiswas/opsimdb/DC2/minion_1016_desc_dithered_v3.db`

@rbiswas4 is there any documentation that lists out the differences/generation of v1-v3 databases? As far as I understand:
- changing the fiveSigmaDepth (any other cols?) in `minion_1016_sqlite.db` --> `minion_1016_desc_v1.db` (Note: this does *not* have the dither columns used in DC, i.e. no random translation dithers and no rotational dithers).
- adding DC1 dither columns from `minion_1016_sqlite_new_dithers.db` to `minion_1016_desc_v1.db` as descDitheredRA, descDitheredDec, descDitheredRotTelPos --> `minion_1016_desc_dithered_v2.db` (Note: the descDithered columns in v2 are no different than the new afterburner output used in DC1; just different names for the same thing.)
- updating descDitheredRA, descDitheredDec, descDitheredRotTelPos in `minion_1016_desc_dithered_v2.db` based on WFD+DDF dithers from me --> `minion_1016_desc_dithered_v3.db`

Please let me know if I'm mistaken about something. Also, I think these should be documented somewhere as the changes are not inferable from the database names.

**Comment by humnaawan** [comment]
@rbiswas4 also, you had mentioned that since there are duplicates entries in OpSim output (visits that are both WFD and DD), we are considering them to WFD only during the database updates. Perhaps that needs to documented somewhere too?

**Comment by rbiswas4** [comment]
@humnaawan Very glad that you are pointing this out and thinking in this direction:
>  changing the fiveSigmaDepth (any other cols?) in minion_1016_sqlite.db --> minion_1016_desc_v1.db (Note: this does not have the dither columns used in DC, i.e. no random translation dithers and no rotational dithers).
 
Correct there are no random dithers etc. , skybrightness columns should also change (that is the cause of changing    fiveSigmaDepths), there is also a change in airmass (more accurate calculations), but that is very small.

> adding DC1 dither columns from minion_1016_sqlite_new_dithers.db to minion_1016_desc_v1.db as descDitheredRA, descDitheredDec, descDitheredRotTelPos --> minion_1016_desc_dithered_v2.db (Note: the descDithered columns in v2 are no different than the new afterburner output used in DC1; just different names for the same thing.)

Correct.

> updating descDitheredRA, descDitheredDec, descDitheredRotTelPos in minion_1016_desc_dithered_v2.db based on WFD+DDF dithers from me --> minion_1016_desc_dithered_v3.db
Correct.  

And I agree with the idea that we should track these. Hence look at the branch https://github.com/LSSTDESC/DC2_Repo/tree/Issue%23110/SurveyDesignTracking (based on Issue 110). The tracking system I proposed is in https://github.com/LSSTDESC/DC2_Repo/tree/Issue%23110/SurveyDesignTracking/Documents/SurveyDesignTracking) The readme contains products and their descriptions, and there is a csv file with filenames https://github.com/LSSTDESC/DC2_Repo/blob/Issue%23110/SurveyDesignTracking/Documents/SurveyDesignTracking/DC2VisitsAndOpSimProducts.csv 

Clearly needs updating after your work :)

**Comment by rbiswas4** [comment]
@humnaawan 

> also, you had mentioned that since there are duplicates entries in OpSim output (visits that are both WFD and DD), we are considering them to WFD only during the database updates. Perhaps that needs to documented somewhere too?

good point too! This should also go into both the tracking that I just talked about and the google doc notes Phil set up directly! Feel free to take the lead on that :)

**Comment by rbiswas4** [comment]
Yes, I think it should be closed.
